version: '3.4'
services:
  mysql:
    hostname: mysql
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shelter